# Site settings
name: Miguel Bonilla
description: "Mobile Developer: Android and iOS (Android Studio, Xamarin Studio) <br>
			  Telecom Product Manager (Product Development, Business Intelligence & Data Mining) <br>
			  Nicaraguan Food Lover"
url: "miguelbonilla.info"


# Delete the lines you don't need
# about 5 elements are recomended
github_username:  mikebonilla
linkedin_username: miguelbonilla
#blog_url: "/blog"
email: mikebonilla@bluetton.com

avatar: yes
avatar_img_path: "imgs/avatarmike.jpeg"
# You can link to your GitHub image. That way it will get updated
# automatically whenever you change your GitHub profile picture
#avatar_img_path: "https://avatars3.githubusercontent.com/u/5114364?v=3&s=460"


front_img: yes
front_img_path: "imgs/background.jpg"
#front_img_path: "https://external.url/image.jpg"


favicon_img: yes
favicon_img_path: "imgs/favicon.ico"
#favicon_img_path: "https://external.url/favicon.ico"


# Build settings
markdown: kramdown
permalink: pretty

destination: docs
